# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  encoding: unicode
  username: lucas
  password: <%= ENV['DB_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: blog_v4_uvr1_dev
test:
  <<: *default
  database: blog_v4_uvr1_test

production:
  <<: *default
  database: blog_v4_uvr1
  url: <%= ENV['DATABASE_URL'] %>

